#!/bin/bash
# =============================================================================
# Setup Custom Domain for Saleor Hub on WOPR Beacon
# =============================================================================
#
# Configures thedudeabides.shop (or any custom domain) to serve the Saleor
# storefront and redirects the wopr.systems URL away from public view.
#
# Prerequisites:
#   1. Custom domain DNS already pointing to the beacon's IP:
#      - A record:    thedudeabides.shop -> <beacon_ip>
#      - CNAME:       www.thedudeabides.shop -> thedudeabides.shop
#
#   2. SSH access to the beacon (dudeabides.wopr.systems)
#
# Usage:
#   ./setup_custom_domain.sh <custom_domain> <beacon_domain>
#
# Example:
#   ./setup_custom_domain.sh thedudeabides.shop dudeabides.wopr.systems
#
# =============================================================================

set -euo pipefail

CUSTOM_DOMAIN="${1:?Usage: $0 <custom_domain> <beacon_domain>}"
BEACON_DOMAIN="${2:?Usage: $0 <custom_domain> <beacon_domain>}"
CADDY_CONFIG="/etc/caddy/Caddyfile"
CADDY_SNIPPETS="/etc/caddy/conf.d"
BACKUP_DIR="/etc/caddy/backups"

echo "============================================="
echo "WOPR Custom Domain Setup"
echo "============================================="
echo "Custom domain:  ${CUSTOM_DOMAIN}"
echo "Beacon domain:  ${BEACON_DOMAIN}"
echo "Caddy config:   ${CADDY_CONFIG}"
echo ""

# Backup current config
mkdir -p "${BACKUP_DIR}"
BACKUP_FILE="${BACKUP_DIR}/Caddyfile.$(date +%Y%m%d_%H%M%S).bak"
cp "${CADDY_CONFIG}" "${BACKUP_FILE}"
echo "Backed up current config to ${BACKUP_FILE}"

# Create the custom domain snippet
mkdir -p "${CADDY_SNIPPETS}"

cat > "${CADDY_SNIPPETS}/custom-domain-${CUSTOM_DOMAIN}.caddy" << 'CADDYEOF'
# =============================================================================
# Custom Domain: CUSTOM_DOMAIN_PLACEHOLDER
# Generated by WOPR setup_custom_domain.sh
# =============================================================================

# Public storefront — no SSO, direct to Saleor
CUSTOM_DOMAIN_PLACEHOLDER {
    # Saleor serves the correct channel based on the Host header
    reverse_proxy saleor:8000 {
        header_up Host {host}
        header_up X-Forwarded-Host {host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Real-IP {remote_host}
    }

    # Security headers
    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "SAMEORIGIN"
        Referrer-Policy "strict-origin-when-cross-origin"
    }

    log {
        output file /var/log/caddy/CUSTOM_DOMAIN_PLACEHOLDER.log
    }
}

# WWW redirect
www.CUSTOM_DOMAIN_PLACEHOLDER {
    redir https://CUSTOM_DOMAIN_PLACEHOLDER{uri} permanent
}
CADDYEOF

# Replace placeholder with actual domain
sed -i "s/CUSTOM_DOMAIN_PLACEHOLDER/${CUSTOM_DOMAIN}/g" \
    "${CADDY_SNIPPETS}/custom-domain-${CUSTOM_DOMAIN}.caddy"

echo "Created custom domain snippet: ${CADDY_SNIPPETS}/custom-domain-${CUSTOM_DOMAIN}.caddy"

# Create the redirect snippet for the wopr.systems store subdomain
cat > "${CADDY_SNIPPETS}/redirect-store-to-custom.caddy" << REDIRECTEOF
# =============================================================================
# Redirect store.${BEACON_DOMAIN} to ${CUSTOM_DOMAIN}
# Public visitors to the wopr.systems URL get redirected to the custom domain.
# =============================================================================

store.${BEACON_DOMAIN} {
    # Redirect all public traffic to the custom domain
    @not_api {
        not path /graphql/* /dashboard/* /media/* /static/*
    }
    handle @not_api {
        redir https://${CUSTOM_DOMAIN}{uri} permanent
    }

    # Keep GraphQL API, Dashboard, and static assets accessible
    # (needed for admin access and API consumers)
    handle {
        forward_auth authentik:9000 {
            uri /outpost.goauthentik.io/auth/caddy
            copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid
            trusted_proxies private_ranges
        }
        reverse_proxy saleor:8000 {
            header_up Host {host}
            header_up X-Forwarded-Host {host}
        }
    }

    log {
        output file /var/log/caddy/store-redirect.log
    }
}
REDIRECTEOF

echo "Created redirect snippet: ${CADDY_SNIPPETS}/redirect-store-to-custom.caddy"

# Ensure the main Caddyfile imports the snippets directory
if ! grep -q "import conf.d/\*" "${CADDY_CONFIG}" 2>/dev/null; then
    echo "" >> "${CADDY_CONFIG}"
    echo "# Custom domain configurations" >> "${CADDY_CONFIG}"
    echo "import conf.d/*" >> "${CADDY_CONFIG}"
    echo "Added 'import conf.d/*' to ${CADDY_CONFIG}"
fi

# Validate the config
echo ""
echo "Validating Caddy configuration..."
if caddy validate --config "${CADDY_CONFIG}" --adapter caddyfile 2>&1; then
    echo "Config valid."
else
    echo "ERROR: Config validation failed. Rolling back..."
    cp "${BACKUP_FILE}" "${CADDY_CONFIG}"
    echo "Rolled back to ${BACKUP_FILE}"
    exit 1
fi

# Reload Caddy
echo ""
echo "Reloading Caddy..."
if systemctl reload caddy 2>/dev/null || caddy reload --config "${CADDY_CONFIG}" --adapter caddyfile; then
    echo "Caddy reloaded successfully."
else
    echo "ERROR: Caddy reload failed. Rolling back..."
    cp "${BACKUP_FILE}" "${CADDY_CONFIG}"
    systemctl reload caddy 2>/dev/null || caddy reload --config "${CADDY_CONFIG}" --adapter caddyfile
    echo "Rolled back to ${BACKUP_FILE}"
    exit 1
fi

# Verify
echo ""
echo "============================================="
echo "SETUP COMPLETE"
echo "============================================="
echo ""
echo "Next steps:"
echo "  1. Point your domain's DNS to the beacon IP:"
echo "     ${CUSTOM_DOMAIN}  A  -> $(curl -s ifconfig.me 2>/dev/null || echo '<beacon_ip>')"
echo ""
echo "  2. Caddy will auto-provision TLS via Let's Encrypt"
echo "     on the first request to https://${CUSTOM_DOMAIN}"
echo ""
echo "  3. Configure Saleor channel domain:"
echo "     In Saleor Dashboard -> Configuration -> Channels"
echo "     Set the storefront domain to: ${CUSTOM_DOMAIN}"
echo ""
echo "  4. Test:"
echo "     curl -I https://${CUSTOM_DOMAIN}"
echo "     curl -I https://store.${BEACON_DOMAIN}  (should 301 to ${CUSTOM_DOMAIN})"
echo ""
echo "============================================="
