# WOPR Stripe Product Catalog
# ============================
#
# This file is auto-generated by scripts/stripe-setup.ps1
# Run that script to populate STRIPE_PRODUCTS and STRIPE_PRICES with real IDs.
#
# For development, this file contains the pricing structure which allows
# the billing module to work before Stripe products are created.

from typing import Dict, Optional, List

# Stripe Product IDs (populated by stripe-setup.ps1)
STRIPE_PRODUCTS: Dict[str, str] = {
    # Will be populated with: "bundle_tier": "prod_xxx"
}

# Stripe Price IDs (populated by stripe-setup.ps1)
STRIPE_PRICES: Dict[str, str] = {
    # Will be populated with: "bundle_tier_monthly": "price_xxx"
}

# Bundle pricing in cents
BUNDLE_PRICING: Dict[str, Dict[str, int]] = {
    # Sovereign Suites
    "starter": {"t1": 1599, "t2": 2599, "t3": 3599},
    "creator": {"t1": 3599, "t2": 5599, "t3": 9599},
    "developer": {"t1": 3599, "t2": 5599, "t3": 9599},
    "professional": {"t1": 6599, "t2": 9599, "t3": 14999},
    "family": {"t1": 4599, "t2": 6599, "t3": 9599},
    "small_business": {"t1": 9599, "t2": 14999, "t3": 19999},
    "enterprise": {"t1": 19999, "t2": 29999, "t3": 0},  # t3 = custom

    # Micro-Bundles
    "meeting_room": {"t1": 1599, "t2": 2599, "t3": 3599},
    "privacy_pack": {"t1": 1599, "t2": 2599, "t3": 3599},
    "writer_studio": {"t1": 1999, "t2": 2999, "t3": 4599},
    "artist_storefront": {"t1": 1999, "t2": 2999, "t3": 4599},
    "podcaster": {"t1": 2599, "t2": 3599, "t3": 5599},
    "freelancer": {"t1": 2599, "t2": 3599, "t3": 5599},
    "musician": {"t1": 2599, "t2": 3599, "t3": 5599},
    "family_hub": {"t1": 2999, "t2": 4599, "t3": 6599},
    "photographer": {"t1": 2999, "t2": 4599, "t3": 6599},
    "bookkeeper": {"t1": 2999, "t2": 4599, "t3": 6599},
    "video_creator": {"t1": 3599, "t2": 5599, "t3": 9599},
    "contractor": {"t1": 3599, "t2": 5599, "t3": 9599},
    "realtor": {"t1": 3599, "t2": 5599, "t3": 9599},
    "educator": {"t1": 3599, "t2": 5599, "t3": 9599},
    "therapist": {"t1": 4599, "t2": 6599, "t3": 12599},
    "legal": {"t1": 4599, "t2": 6599, "t3": 12599},
}

# Bundle metadata
BUNDLE_INFO: Dict[str, Dict[str, str]] = {
    # Sovereign Suites
    "starter": {
        "name": "Starter Sovereign Suite",
        "description": "Drive, calendar, notes, tasks, passwords - the essentials to ditch Big Tech.",
        "type": "sovereign",
    },
    "creator": {
        "name": "Creator Sovereign Suite",
        "description": "Blog, portfolio, online store, newsletter - monetize your work.",
        "type": "sovereign",
    },
    "developer": {
        "name": "Developer Sovereign Suite",
        "description": "Git hosting, CI/CD, code editor, Reactor AI coding assistant.",
        "type": "sovereign",
    },
    "professional": {
        "name": "Professional Sovereign Suite",
        "description": "Creator + Developer combined + DEFCON ONE security gateway.",
        "type": "sovereign",
    },
    "family": {
        "name": "Family Sovereign Suite",
        "description": "6 user accounts, shared photos, shared passwords, family calendar.",
        "type": "sovereign",
    },
    "small_business": {
        "name": "Small Business Sovereign Suite",
        "description": "CRM, team chat, office suite, DEFCON ONE + Reactor AI.",
        "type": "sovereign",
    },
    "enterprise": {
        "name": "Enterprise Sovereign Suite",
        "description": "Unlimited users, custom integrations, dedicated support, full AI suite.",
        "type": "sovereign",
    },

    # Micro-Bundles
    "meeting_room": {
        "name": "Meeting Room",
        "description": "Video calls, scheduling, collaborative notes - replace Zoom.",
        "type": "micro",
    },
    "privacy_pack": {
        "name": "Privacy Pack",
        "description": "Encrypted storage, password manager, private VPN - total privacy.",
        "type": "micro",
    },
    "writer_studio": {
        "name": "Writer's Studio",
        "description": "Blog, newsletter, research archive, bookmarks - replace Substack.",
        "type": "micro",
    },
    "artist_storefront": {
        "name": "Artist Storefront",
        "description": "Online store, portfolio, photo galleries - replace Etsy.",
        "type": "micro",
    },
    "podcaster": {
        "name": "Podcaster Pack",
        "description": "Podcast hosting, show notes blog, listener analytics - own your feed.",
        "type": "micro",
    },
    "freelancer": {
        "name": "Freelancer Essentials",
        "description": "Invoicing, scheduling, client contacts - run your business.",
        "type": "micro",
    },
    "musician": {
        "name": "Musician Bundle",
        "description": "Music streaming, artist website, merch store - own your music.",
        "type": "micro",
    },
    "family_hub": {
        "name": "Family Hub",
        "description": "Shared drive, photos, passwords for 6 family members.",
        "type": "micro",
    },
    "photographer": {
        "name": "Photographer Pro",
        "description": "Photo library, client galleries, portfolio, print sales.",
        "type": "micro",
    },
    "bookkeeper": {
        "name": "Bookkeeper Bundle",
        "description": "Document scanner, client portal, secure messaging.",
        "type": "micro",
    },
    "video_creator": {
        "name": "Video Creator",
        "description": "Video hosting, community blog, paid memberships - replace YouTube.",
        "type": "micro",
    },
    "contractor": {
        "name": "Contractor Pro",
        "description": "Digital contracts, project management, time tracking.",
        "type": "micro",
    },
    "realtor": {
        "name": "Real Estate Agent",
        "description": "Lead CRM, listing photos, digital contracts.",
        "type": "micro",
    },
    "educator": {
        "name": "Educator Suite",
        "description": "Virtual classroom, whiteboard, file sharing for students.",
        "type": "micro",
    },
    "therapist": {
        "name": "Therapist/Coach",
        "description": "Secure video sessions, encrypted notes, client portal - HIPAA-ready.",
        "type": "micro",
    },
    "legal": {
        "name": "Legal Lite",
        "description": "Document management, e-signatures, secure client portal.",
        "type": "micro",
    },
}

# Tier metadata
TIER_INFO: Dict[str, Dict[str, str]] = {
    "t1": {"name": "Tier 1", "storage": "50GB", "description": "50GB storage"},
    "t2": {"name": "Tier 2", "storage": "200GB", "description": "200GB storage"},
    "t3": {"name": "Tier 3", "storage": "500GB+", "description": "500GB+ storage"},
}


# Helper functions
def get_price_id(bundle_id: str, tier: str, period: str = "monthly") -> Optional[str]:
    """Get Stripe price ID for a bundle/tier/period combination."""
    key = f"{bundle_id}_{tier}_{period}"
    return STRIPE_PRICES.get(key)


def get_product_id(bundle_id: str, tier: str) -> Optional[str]:
    """Get Stripe product ID for a bundle/tier combination."""
    key = f"{bundle_id}_{tier}"
    return STRIPE_PRODUCTS.get(key)


def get_price_cents(bundle_id: str, tier: str) -> int:
    """Get monthly price in cents for a bundle/tier."""
    bundle = BUNDLE_PRICING.get(bundle_id, {})
    return bundle.get(tier, 0)


def get_price_display(bundle_id: str, tier: str) -> str:
    """Get formatted price string (e.g., '$15.99')."""
    cents = get_price_cents(bundle_id, tier)
    if cents == 0:
        return "Custom"
    return f"${cents / 100:.2f}"


def get_yearly_price_cents(bundle_id: str, tier: str) -> int:
    """Get yearly price in cents (2 months free)."""
    monthly = get_price_cents(bundle_id, tier)
    if monthly == 0:
        return 0
    return monthly * 10  # 10 months instead of 12


def get_bundle_info(bundle_id: str) -> Optional[Dict[str, str]]:
    """Get bundle metadata."""
    return BUNDLE_INFO.get(bundle_id)


def get_tier_info(tier: str) -> Optional[Dict[str, str]]:
    """Get tier metadata."""
    return TIER_INFO.get(tier)


def get_all_bundles() -> List[str]:
    """Get list of all bundle IDs."""
    return list(BUNDLE_PRICING.keys())


def get_sovereign_suites() -> List[str]:
    """Get list of Sovereign Suite bundle IDs."""
    return [b for b, info in BUNDLE_INFO.items() if info.get("type") == "sovereign"]


def get_micro_bundles() -> List[str]:
    """Get list of Micro-Bundle IDs."""
    return [b for b, info in BUNDLE_INFO.items() if info.get("type") == "micro"]


def is_valid_bundle(bundle_id: str) -> bool:
    """Check if bundle ID is valid."""
    return bundle_id in BUNDLE_PRICING


def is_valid_tier(tier: str) -> bool:
    """Check if tier is valid."""
    return tier in TIER_INFO


def get_bundle_for_display(bundle_id: str, tier: str) -> Dict:
    """Get complete bundle info for display in UI."""
    info = get_bundle_info(bundle_id) or {}
    tier_info = get_tier_info(tier) or {}

    return {
        "bundle_id": bundle_id,
        "tier": tier,
        "name": info.get("name", bundle_id),
        "description": info.get("description", ""),
        "type": info.get("type", "unknown"),
        "storage": tier_info.get("storage", ""),
        "price_monthly": get_price_display(bundle_id, tier),
        "price_monthly_cents": get_price_cents(bundle_id, tier),
        "price_yearly_cents": get_yearly_price_cents(bundle_id, tier),
    }
