# WOPR Stripe Product Catalog
# ============================
#
# This file is auto-generated by scripts/stripe-setup.ps1
# Run that script to populate STRIPE_PRODUCTS and STRIPE_PRICES with real IDs.
#
# For development, this file contains the pricing structure which allows
# the billing module to work before Stripe products are created.

import json
import os
from pathlib import Path
from typing import Dict, Optional, List

# Stripe Product IDs (populated from live Stripe account)
STRIPE_PRODUCTS: Dict[str, str] = {
    "artist_storefront_t1": "prod_TrXjNsw2Od6zYu",
    "artist_storefront_t2": "prod_TrXjNsw2Od6zYu",
    "artist_storefront_t3": "prod_TrXjNsw2Od6zYu",
    "bookkeeper_t1": "prod_TrXk6fpCYEsylz",
    "bookkeeper_t2": "prod_TrXk6fpCYEsylz",
    "bookkeeper_t3": "prod_TrXk6fpCYEsylz",
    "contractor_t1": "prod_TrXkAdeG4gyLd4",
    "contractor_t2": "prod_TrXkAdeG4gyLd4",
    "contractor_t3": "prod_TrXkAdeG4gyLd4",
    "creator_t1": "prod_TrXixqcOUYHC7t",
    "creator_t2": "prod_TrXixqcOUYHC7t",
    "creator_t3": "prod_TrXixqcOUYHC7t",
    "developer_t1": "prod_TrXiK3v47oYGBq",
    "developer_t2": "prod_TrXiK3v47oYGBq",
    "developer_t3": "prod_TrXiK3v47oYGBq",
    "educator_t1": "prod_TrXktzU8d2Ihym",
    "educator_t2": "prod_TrXktzU8d2Ihym",
    "educator_t3": "prod_TrXktzU8d2Ihym",
    "enterprise_t1": "prod_TrXi0jsUZi5dzf",
    "enterprise_t2": "prod_TrXi0jsUZi5dzf",
    "enterprise_t3": "prod_TrXi0jsUZi5dzf",
    "family_hub_t1": "prod_TrXkssQLpeanRX",
    "family_hub_t2": "prod_TrXkssQLpeanRX",
    "family_hub_t3": "prod_TrXkssQLpeanRX",
    "family_t1": "prod_TrXiBti2tyS8Ws",
    "family_t2": "prod_TrXiBti2tyS8Ws",
    "family_t3": "prod_TrXiBti2tyS8Ws",
    "freelancer_t1": "prod_TrXkQZGmy2TIta",
    "freelancer_t2": "prod_TrXkQZGmy2TIta",
    "freelancer_t3": "prod_TrXkQZGmy2TIta",
    "legal_t1": "prod_TrXkfKwnIdTA5r",
    "legal_t2": "prod_TrXkfKwnIdTA5r",
    "legal_t3": "prod_TrXkfKwnIdTA5r",
    "meeting_room_t1": "prod_TrXj1X9Wzcs1nW",
    "meeting_room_t2": "prod_TrXj1X9Wzcs1nW",
    "meeting_room_t3": "prod_TrXj1X9Wzcs1nW",
    "musician_t1": "prod_TrXkmpSlaPR5lZ",
    "musician_t2": "prod_TrXkmpSlaPR5lZ",
    "musician_t3": "prod_TrXkmpSlaPR5lZ",
    "personal_productivity_t1": "prod_TrXjAFAI39mz2y",
    "personal_productivity_t2": "prod_TrXjAFAI39mz2y",
    "personal_productivity_t3": "prod_TrXjAFAI39mz2y",
    "photographer_t1": "prod_TrXkNBqRqNZYUi",
    "photographer_t2": "prod_TrXkNBqRqNZYUi",
    "photographer_t3": "prod_TrXkNBqRqNZYUi",
    "podcaster_t1": "prod_TrXk8s3xagGO7T",
    "podcaster_t2": "prod_TrXk8s3xagGO7T",
    "podcaster_t3": "prod_TrXk8s3xagGO7T",
    "privacy_pack_t1": "prod_TrXjT4BXIUOGG3",
    "privacy_pack_t2": "prod_TrXjT4BXIUOGG3",
    "privacy_pack_t3": "prod_TrXjT4BXIUOGG3",
    "professional_t1": "prod_TrXiaP801S1Jgr",
    "professional_t2": "prod_TrXiaP801S1Jgr",
    "professional_t3": "prod_TrXiaP801S1Jgr",
    "realtor_t1": "prod_TrXki30tDs1o6k",
    "realtor_t2": "prod_TrXki30tDs1o6k",
    "realtor_t3": "prod_TrXki30tDs1o6k",
    "small_business_t1": "prod_TrXiN5xCJsTAsb",
    "small_business_t2": "prod_TrXiN5xCJsTAsb",
    "small_business_t3": "prod_TrXiN5xCJsTAsb",
    "starter_t1": "prod_TrXisBIytrB2Vw",
    "starter_t2": "prod_TrXisBIytrB2Vw",
    "starter_t3": "prod_TrXisBIytrB2Vw",
    "therapist_t1": "prod_TrXkUtQqIcsK5U",
    "therapist_t2": "prod_TrXkUtQqIcsK5U",
    "therapist_t3": "prod_TrXkUtQqIcsK5U",
    "video_creator_t1": "prod_TrXkcznTPkIwIG",
    "video_creator_t2": "prod_TrXkcznTPkIwIG",
    "video_creator_t3": "prod_TrXkcznTPkIwIG",
    "writer_studio_t1": "prod_TrXj5iLZwM3yCm",
    "writer_studio_t2": "prod_TrXj5iLZwM3yCm",
    "writer_studio_t3": "prod_TrXj5iLZwM3yCm",
}

# Stripe Price IDs (populated from live Stripe account)
STRIPE_PRICES: Dict[str, str] = {
    "artist_storefront_t1_monthly": "price_1StoeV2ZMY5KYPjWixxiD5w3",
    "artist_storefront_t2_monthly": "price_1StoeW2ZMY5KYPjWyVMveMlq",
    "artist_storefront_t3_monthly": "price_1StoeW2ZMY5KYPjWs0R8ea1Z",
    "bookkeeper_t1_monthly": "price_1Stoek2ZMY5KYPjWdFdZQSpn",
    "bookkeeper_t2_monthly": "price_1Stoek2ZMY5KYPjWL6YjJTrX",
    "bookkeeper_t3_monthly": "price_1Stoel2ZMY5KYPjWthPzi03g",
    "contractor_t1_monthly": "price_1Stoeq2ZMY5KYPjWheLrFr9r",
    "contractor_t2_monthly": "price_1Stoer2ZMY5KYPjWk1xXjf2Z",
    "contractor_t3_monthly": "price_1Stoes2ZMY5KYPjWVdK6sYHn",
    "creator_t1_monthly": "price_1Stod72ZMY5KYPjW2OEDlZrW",
    "creator_t2_monthly": "price_1Stod72ZMY5KYPjWDlGJmyYe",
    "creator_t3_monthly": "price_1Stod82ZMY5KYPjWjYoxjbX9",
    "developer_t1_monthly": "price_1StodA2ZMY5KYPjWJsuYiAmZ",
    "developer_t2_monthly": "price_1StodB2ZMY5KYPjWHpNuWKZM",
    "developer_t3_monthly": "price_1StodC2ZMY5KYPjWFlkijebi",
    "educator_t1_monthly": "price_1Stoex2ZMY5KYPjWvBI4BKNS",
    "educator_t2_monthly": "price_1Stoey2ZMY5KYPjWjUhAliz2",
    "educator_t3_monthly": "price_1Stoey2ZMY5KYPjWYL64X4Mc",
    "enterprise_t1_monthly": "price_1StodN2ZMY5KYPjWMgGRjIrY",
    "enterprise_t2_monthly": "price_1StodO2ZMY5KYPjW0LWChnNX",
    "enterprise_t3_monthly": "price_1StodP2ZMY5KYPjW3AmwEF5i",
    "family_hub_t1_monthly": "price_1Stoee2ZMY5KYPjWODMPpryK",
    "family_hub_t2_monthly": "price_1Stoef2ZMY5KYPjWpjfTjJ3z",
    "family_hub_t3_monthly": "price_1Stoef2ZMY5KYPjWbuq05jCV",
    "family_t1_monthly": "price_1StodG2ZMY5KYPjWmt5BGgsk",
    "family_t2_monthly": "price_1StodH2ZMY5KYPjWan1I2jBZ",
    "family_t3_monthly": "price_1StodI2ZMY5KYPjW6ViYVhAk",
    "freelancer_t1_monthly": "price_1Stoea2ZMY5KYPjWHeDlWYxB",
    "freelancer_t2_monthly": "price_1Stoea2ZMY5KYPjW3xQ6KNGy",
    "freelancer_t3_monthly": "price_1Stoeb2ZMY5KYPjWqjxdv573",
    "legal_t1_monthly": "price_1Stof42ZMY5KYPjWrY5vsyZx",
    "legal_t2_monthly": "price_1Stof42ZMY5KYPjWWD3zaBd7",
    "legal_t3_monthly": "price_1Stof52ZMY5KYPjWJQqQs1HQ",
    "meeting_room_t1_monthly": "price_1StoeO2ZMY5KYPjWZBF2ZR2x",
    "meeting_room_t2_monthly": "price_1StoeO2ZMY5KYPjWMNeJf4Iq",
    "meeting_room_t3_monthly": "price_1StoeP2ZMY5KYPjWamWhn3oq",
    "musician_t1_monthly": "price_1Stoec2ZMY5KYPjWSh7ERPGi",
    "musician_t2_monthly": "price_1Stoec2ZMY5KYPjW6SdvljlQ",
    "musician_t3_monthly": "price_1Stoed2ZMY5KYPjWhBcRIB4N",
    "personal_productivity_t1_monthly": "price_1StoeM2ZMY5KYPjWyqsszDxL",
    "personal_productivity_t2_monthly": "price_1StoeM2ZMY5KYPjWEHmphaxx",
    "personal_productivity_t3_monthly": "price_1StoeN2ZMY5KYPjWuYbW3bJX",
    "photographer_t1_monthly": "price_1Stoeh2ZMY5KYPjWDiJkVnGu",
    "photographer_t2_monthly": "price_1Stoeh2ZMY5KYPjWj5Ym9CsA",
    "photographer_t3_monthly": "price_1Stoei2ZMY5KYPjWlcOtqFlF",
    "podcaster_t1_monthly": "price_1StoeX2ZMY5KYPjWxVZRz1U3",
    "podcaster_t2_monthly": "price_1StoeY2ZMY5KYPjWNKgmIgEo",
    "podcaster_t3_monthly": "price_1StoeZ2ZMY5KYPjW5eZwSSon",
    "privacy_pack_t1_monthly": "price_1StoeQ2ZMY5KYPjWQMTghNvV",
    "privacy_pack_t2_monthly": "price_1StoeR2ZMY5KYPjWyNqf8jvX",
    "privacy_pack_t3_monthly": "price_1StoeR2ZMY5KYPjWIUb9RtCf",
    "professional_t1_monthly": "price_1StodD2ZMY5KYPjWjLepiFRQ",
    "professional_t2_monthly": "price_1StodE2ZMY5KYPjWX6ChOsWp",
    "professional_t3_monthly": "price_1StodF2ZMY5KYPjWM9LzQEmQ",
    "realtor_t1_monthly": "price_1Stoeu2ZMY5KYPjWXgh1Vx6R",
    "realtor_t2_monthly": "price_1Stoeu2ZMY5KYPjWEkgzWmJY",
    "realtor_t3_monthly": "price_1Stoev2ZMY5KYPjWsBe9qAp5",
    "small_business_t1_monthly": "price_1StodK2ZMY5KYPjWTtw7xOC5",
    "small_business_t2_monthly": "price_1StodL2ZMY5KYPjWs7cRgusn",
    "small_business_t3_monthly": "price_1StodM2ZMY5KYPjW58o2KwiR",
    "starter_t1_monthly": "price_1Stod32ZMY5KYPjWtWz0tqaN",
    "starter_t2_monthly": "price_1Stod42ZMY5KYPjW0YVSoy4W",
    "starter_t3_monthly": "price_1Stod52ZMY5KYPjWapNDg5Hc",
    "therapist_t1_monthly": "price_1Stof02ZMY5KYPjWQWsH8wQv",
    "therapist_t2_monthly": "price_1Stof12ZMY5KYPjWUykU1Zna",
    "therapist_t3_monthly": "price_1Stof22ZMY5KYPjWSSWpruhM",
    "video_creator_t1_monthly": "price_1Stoen2ZMY5KYPjWzU966J5c",
    "video_creator_t2_monthly": "price_1Stoeo2ZMY5KYPjWiEOJbgx4",
    "video_creator_t3_monthly": "price_1Stoeo2ZMY5KYPjWLe1W3tLl",
    "writer_studio_t1_monthly": "price_1StoeT2ZMY5KYPjWv5KEsfSZ",
    "writer_studio_t2_monthly": "price_1StoeT2ZMY5KYPjWuyhdxeAQ",
    "writer_studio_t3_monthly": "price_1StoeU2ZMY5KYPjWMKAyQWS9",
}

# Load test prices if STRIPE_PRICE_MODE=test
if os.environ.get("STRIPE_PRICE_MODE", "live") == "test":
    _test_price_file = Path(__file__).parent / "bundles" / "stripe_prices_test.json"
    if _test_price_file.exists():
        with open(_test_price_file) as _f:
            _test_data = json.load(_f)
        _test_prices: Dict[str, str] = {}
        _tier_map = {"tier_1": "t1", "tier_2": "t2", "tier_3": "t3"}
        # Map "smallbusiness" -> "small_business" to match catalog keys
        _bundle_renames = {"smallbusiness": "small_business"}
        for _btype in ("sovereign", "micro"):
            for _bid, _bdata in _test_data.get(_btype, {}).items():
                _catalog_bid = _bundle_renames.get(_bid, _bid)
                for _tkey, _price_id in _bdata.get("prices", {}).items():
                    _tier = _tier_map.get(_tkey, _tkey)
                    _test_prices[f"{_catalog_bid}_{_tier}_monthly"] = _price_id
        STRIPE_PRICES.update(_test_prices)

# Bundle pricing in cents (updated Feb 2026 — aligned with actual VPS costs)
BUNDLE_PRICING: Dict[str, Dict[str, int]] = {
    # Sovereign Suites
    "starter": {"t1": 2999, "t2": 4599, "t3": 6599},
    "creator": {"t1": 5599, "t2": 7999, "t3": 11999},
    "developer": {"t1": 5599, "t2": 7999, "t3": 11999},
    "professional": {"t1": 9999, "t2": 14999, "t3": 19999},
    "family": {"t1": 5599, "t2": 7999, "t3": 11999},
    "small_business": {"t1": 12999, "t2": 17999, "t3": 24999},
    "enterprise": {"t1": 24999, "t2": 34999, "t3": 0},  # t3 = custom

    # Light Micro-Bundles (4GB MEDIUM VPS)
    "personal_productivity": {"t1": 2999, "t2": 4599, "t3": 6599},
    "meeting_room": {"t1": 2999, "t2": 4599, "t3": 6599},
    "privacy_pack": {"t1": 2999, "t2": 4599, "t3": 6599},
    "writer_studio": {"t1": 2999, "t2": 4599, "t3": 6599},
    "podcaster": {"t1": 3599, "t2": 5599, "t3": 7999},
    "freelancer": {"t1": 3599, "t2": 5599, "t3": 7999},
    "contractor": {"t1": 3599, "t2": 5599, "t3": 7999},
    "musician": {"t1": 3599, "t2": 5599, "t3": 7999},
    "bookkeeper": {"t1": 3599, "t2": 5599, "t3": 7999},

    # Medium Micro-Bundles (8GB HIGH VPS)
    "artist_storefront": {"t1": 4599, "t2": 6599, "t3": 9599},
    "family_hub": {"t1": 4599, "t2": 6599, "t3": 9599},
    "photographer": {"t1": 5599, "t2": 7999, "t3": 11999},
    "video_creator": {"t1": 4599, "t2": 6599, "t3": 9599},
    "realtor": {"t1": 4599, "t2": 6599, "t3": 9599},
    "educator": {"t1": 4599, "t2": 6599, "t3": 9599},
    "therapist": {"t1": 5599, "t2": 7999, "t3": 11999},
    "legal": {"t1": 5599, "t2": 7999, "t3": 11999},

    # Add-ons
    "ollama_addon": {"t1": 0, "t2": 1499, "t3": 1499},  # Requires T2+ VPS
    # Specialty Bundles
    "DEFCON_ONE": {"t1": 7999, "t2": 11999, "t3": 17999},  # Security premium
    "REACTOR_AI": {"t1": 9999, "t2": 14999, "t3": 24999},  # AI premium
}

# Bundle metadata
BUNDLE_INFO: Dict[str, Dict[str, str]] = {
    # Sovereign Suites
    "starter": {
        "name": "Starter Sovereign Suite",
        "description": "Drive, calendar, notes, tasks, passwords - the essentials to ditch Big Tech.",
        "type": "sovereign",
    },
    "creator": {
        "name": "Creator Sovereign Suite",
        "description": "Blog, portfolio, online store, newsletter - monetize your work.",
        "type": "sovereign",
    },
    "developer": {
        "name": "Developer Sovereign Suite",
        "description": "Git hosting, CI/CD, code editor, Reactor AI coding assistant.",
        "type": "sovereign",
    },
    "professional": {
        "name": "Professional Sovereign Suite",
        "description": "Creator + Developer combined + DEFCON ONE security gateway.",
        "type": "sovereign",
    },
    "family": {
        "name": "Family Sovereign Suite",
        "description": "6 user accounts, shared photos, shared passwords, family calendar.",
        "type": "sovereign",
    },
    "small_business": {
        "name": "Small Business Sovereign Suite",
        "description": "CRM, team chat, office suite, DEFCON ONE + Reactor AI.",
        "type": "sovereign",
    },
    "enterprise": {
        "name": "Enterprise Sovereign Suite",
        "description": "Unlimited users, custom integrations, dedicated support, full AI suite.",
        "type": "sovereign",
    },

    # Micro-Bundles
    "meeting_room": {
        "name": "Meeting Room",
        "description": "Video calls, scheduling, collaborative notes - replace Zoom.",
        "type": "micro",
    },
    "privacy_pack": {
        "name": "Privacy Pack",
        "description": "Encrypted storage, password manager, private VPN - total privacy.",
        "type": "micro",
    },
    "writer_studio": {
        "name": "Writer's Studio",
        "description": "Blog, newsletter, research archive, bookmarks - replace Substack.",
        "type": "micro",
    },
    "artist_storefront": {
        "name": "Artist Storefront",
        "description": "Online store, portfolio, photo galleries - replace Etsy.",
        "type": "micro",
    },
    "podcaster": {
        "name": "Podcaster Pack",
        "description": "Podcast hosting, show notes blog, listener analytics - own your feed.",
        "type": "micro",
    },
    "freelancer": {
        "name": "Freelancer Essentials",
        "description": "Invoicing, scheduling, client contacts - run your business.",
        "type": "micro",
    },
    "musician": {
        "name": "Musician Bundle",
        "description": "Music streaming, artist website, merch store - own your music.",
        "type": "micro",
    },
    "family_hub": {
        "name": "Family Hub",
        "description": "Shared drive, photos, passwords for 6 family members.",
        "type": "micro",
    },
    "photographer": {
        "name": "Photographer Pro",
        "description": "Photo library, client galleries, portfolio, print sales.",
        "type": "micro",
    },
    "bookkeeper": {
        "name": "Bookkeeper Bundle",
        "description": "Document scanner, client portal, secure messaging.",
        "type": "micro",
    },
    "video_creator": {
        "name": "Video Creator",
        "description": "Video hosting, community blog, paid memberships - replace YouTube.",
        "type": "micro",
    },
    "contractor": {
        "name": "Contractor Pro",
        "description": "Digital contracts, project management, time tracking.",
        "type": "micro",
    },
    "realtor": {
        "name": "Real Estate Agent",
        "description": "Lead CRM, listing photos, digital contracts.",
        "type": "micro",
    },
    "educator": {
        "name": "Educator Suite",
        "description": "Virtual classroom, whiteboard, file sharing for students.",
        "type": "micro",
    },
    "therapist": {
        "name": "Therapist/Coach",
        "description": "Secure video sessions, encrypted notes, client portal - HIPAA-ready.",
        "type": "micro",
    },
    "legal": {
        "name": "Legal Lite",
        "description": "Document management, e-signatures, secure client portal.",
        "type": "micro",
    },
}

# Tier metadata
TIER_INFO: Dict[str, Dict[str, str]] = {
    "t1": {"name": "Tier 1", "storage": "50GB", "description": "50GB storage"},
    "t2": {"name": "Tier 2", "storage": "200GB", "description": "200GB storage"},
    "t3": {"name": "Tier 3", "storage": "500GB+", "description": "500GB+ storage"},
}


# Helper functions
def get_price_id(bundle_id: str, tier: str, period: str = "monthly") -> Optional[str]:
    """Get Stripe price ID for a bundle/tier/period combination."""
    key = f"{bundle_id}_{tier}_{period}"
    return STRIPE_PRICES.get(key)


def get_product_id(bundle_id: str, tier: str) -> Optional[str]:
    """Get Stripe product ID for a bundle/tier combination."""
    key = f"{bundle_id}_{tier}"
    return STRIPE_PRODUCTS.get(key)


def get_price_cents(bundle_id: str, tier: str) -> int:
    """Get monthly price in cents for a bundle/tier."""
    bundle = BUNDLE_PRICING.get(bundle_id, {})
    return bundle.get(tier, 0)


def get_price_display(bundle_id: str, tier: str) -> str:
    """Get formatted price string (e.g., '$15.99')."""
    cents = get_price_cents(bundle_id, tier)
    if cents == 0:
        return "Custom"
    return f"${cents / 100:.2f}"


def get_yearly_price_cents(bundle_id: str, tier: str) -> int:
    """Get yearly price in cents (2 months free)."""
    monthly = get_price_cents(bundle_id, tier)
    if monthly == 0:
        return 0
    return monthly * 10  # 10 months instead of 12


def get_bundle_info(bundle_id: str) -> Optional[Dict[str, str]]:
    """Get bundle metadata."""
    return BUNDLE_INFO.get(bundle_id)


def get_tier_info(tier: str) -> Optional[Dict[str, str]]:
    """Get tier metadata."""
    return TIER_INFO.get(tier)


def get_all_bundles() -> List[str]:
    """Get list of all bundle IDs."""
    return list(BUNDLE_PRICING.keys())


def get_sovereign_suites() -> List[str]:
    """Get list of Sovereign Suite bundle IDs."""
    return [b for b, info in BUNDLE_INFO.items() if info.get("type") == "sovereign"]


def get_micro_bundles() -> List[str]:
    """Get list of Micro-Bundle IDs."""
    return [b for b, info in BUNDLE_INFO.items() if info.get("type") == "micro"]


def is_valid_bundle(bundle_id: str) -> bool:
    """Check if bundle ID is valid."""
    return bundle_id in BUNDLE_PRICING


def is_valid_tier(tier: str) -> bool:
    """Check if tier is valid."""
    return tier in TIER_INFO


def get_bundle_for_display(bundle_id: str, tier: str) -> Dict:
    """Get complete bundle info for display in UI."""
    info = get_bundle_info(bundle_id) or {}
    tier_info = get_tier_info(tier) or {}

    return {
        "bundle_id": bundle_id,
        "tier": tier,
        "name": info.get("name", bundle_id),
        "description": info.get("description", ""),
        "type": info.get("type", "unknown"),
        "storage": tier_info.get("storage", ""),
        "price_monthly": get_price_display(bundle_id, tier),
        "price_monthly_cents": get_price_cents(bundle_id, tier),
        "price_yearly_cents": get_yearly_price_cents(bundle_id, tier),
    }
